name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint commit messages
        run: echo "Skipping commit linting for now"

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # Store the new version number as an output variable
      - name: Get version from package.json
        id: package-version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

  update-submodule:
    name: Update hassio-addons Submodule
    runs-on: ubuntu-latest
    needs: [release]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.release.result == 'success'
    steps:
      - name: Checkout hassio-addons repository
        uses: actions/checkout@v4
        with:
          repository: saya6k/hassio-addons
          token: ${{ secrets.HASSIO_ADDONS_TOKEN }}
          path: hassio-addons
      
      - name: Setup Git configuration
        working-directory: hassio-addons
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      
      - name: Check if submodule exists
        id: check-submodule
        working-directory: hassio-addons
        run: |
          if grep -q "brother-ql-web" .gitmodules 2>/dev/null; then
            echo "SUBMODULE_EXISTS=true" >> $GITHUB_OUTPUT
          else
            echo "SUBMODULE_EXISTS=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Update existing submodule
        if: steps.check-submodule.outputs.SUBMODULE_EXISTS == 'true'
        working-directory: hassio-addons
        run: |
          # More robust submodule update that doesn't fail if there are issues with other submodules
          git config -f .gitmodules --get-regexp '^submodule\.brother-ql-web\.path$' || true
          
          # Check if the directory exists and is a git repository
          if [ -d "brother-ql-web" ] && [ -d "brother-ql-web/.git" ]; then
            cd brother-ql-web
            git fetch
            git checkout main
            git pull
            cd ..
          else
            # If directory doesn't exist or isn't a git repo, initialize just this submodule
            git submodule init mcp-grocy-api
            git submodule update --remote mcp-grocy-api
          fi
          
          # Commit the updated submodule
          git add brother-ql-web
          git commit -m "chore: update brother-ql-web submodule to latest version" || echo "No changes to commit"
          git push || echo "No changes to push"
      
      - name: Check and update gitignore
        if: steps.check-submodule.outputs.SUBMODULE_EXISTS == 'false'
        working-directory: hassio-addons
        run: |
          # Check if brother-ql-web is in .gitignore
          if grep -q "brother-ql-web" .gitignore 2>/dev/null; then
            # Remove or comment out the line from .gitignore
            sed -i 's/brother-ql-web/#brother-ql-web - submodule now/g' .gitignore
            git add .gitignore
            git commit -m "chore: update .gitignore to allow brother-ql-web submodule"
            git push
          fi
      
      - name: Add new submodule
        if: steps.check-submodule.outputs.SUBMODULE_EXISTS == 'false'
        working-directory: hassio-addons
        run: |
          # Add the new submodule with force flag
          git submodule add -f https://github.com/saya6k/hassio-addon-brother-ql-web.git brother-ql-web
          
          # Directly initialize just this submodule without trying to init others
          cd brother-ql-web
          git checkout main
          cd ..
          
          # Commit the new submodule
          git add .gitmodules hassio-addon-brother-ql-web
          git commit -m "chore: add hassio-addon-brother-ql-web submodule"
          git push
